### PR TITLE
Added blinky test, modified test cmake

### PR DESCRIPTION
**Pull request by akeener97**
Added an initial blinky test. Confirmed build system will compile the test without an external project.

### CODE REVIEW

**Comment by Arvind-Srinivasan** [comment]
Whats the deal with this not building? Is that cause concourse is down?

**Comment by akeener97** [comment]
> Whats the deal with this not building? Is that cause concourse is down?

I just resolved the pipeline issue. Should build momentarily.

**Comment by akeener97** [comment]
I just fixed the pipeline issue. It will be built in the next 10 min.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by akeener97** [comment]
Closing as these changes are already reflected in PR #32

**Pull request closed without merging**
